const dict = {
  ar: {
    login: 'تسجيل الدخول', email: 'البريد', password: 'كلمة المرور', dashboard: 'الرئيسية', chat: 'المحادثات', providers: 'المزوّدات', integrations: 'التكاملات', terminal: 'الطرفية', settings: 'الإعدادات', send: 'إرسال', newChat: 'محادثة جديدة', addProvider: 'حفظ المزوّد', addIntegration: 'حفظ التكامل', model: 'النموذج', type: 'النوع', apiKey: 'مفتاح API', baseUrl: 'رابط API', name: 'الاسم', welcome: 'مرحبًا بك في Moataz AI', hero: 'منصة موحدة للمحادثات والوكلاء ومزوّدي النماذج وGitHub وTelegram.', save: 'حفظ', tools: 'الأدوات', light: 'نهاري', dark: 'ليلي', language: 'اللغة', message: 'اكتب رسالتك أو مهمتك…', theme: 'المظهر', logout: 'تسجيل الخروج', loading: 'جارٍ التحميل…', testConnection: 'اختبار الاتصال', testing: 'جارٍ الاختبار…', saving: 'جارٍ الحفظ…', verified: 'تم التحقق', failed: 'فشل التحقق', untested: 'لم يُختبر', edit: 'تعديل', delete: 'حذف', cancel: 'إلغاء', refresh: 'تحديث', status: 'الحالة', providerRequired: 'أضف مزودًا أو اختر مزودًا للمحادثة.', noProviders: 'لا توجد مزودات بعد.', noIntegrations: 'لا توجد تكاملات بعد.', noChats: 'ابدأ محادثة جديدة.', chatMode: 'وضع المحادثة', agentMode: 'وكيل بالأدوات', simpleChat: 'محادثة عادية', selectProvider: 'اختر مزودًا', selectModel: 'النموذج المستخدم', connectionSuccessful: 'الاتصال ناجح', token: 'التوكن', allowedChatIds: 'معرّفات محادثات Telegram المسموحة', allowedChatIdsHint: 'افصل بين المعرّفات بفواصل. يلزم معرف واحد على الأقل لتشغيل polling.', integrationIdentity: 'هوية التكامل', systemHealth: 'حالة النظام', database: 'قاعدة البيانات', uptime: 'مدة التشغيل', configuredProviders: 'المزوّدات المضافة', telegramBots: 'بوتات Telegram', available: 'متاح', unavailable: 'غير متاح', terminalDisabled: 'الطرفية معطلة في الإنتاج دون Sandbox خارجي.', menu: 'القائمة', close: 'إغلاق', retry: 'إعادة المحاولة', clear: 'مسح', conversationSettings: 'إعدادات المحادثة', providerSaved: 'تم حفظ المزوّد. اختبر الاتصال قبل استخدامه.', integrationSaved: 'تم حفظ التكامل. اختبر الاتصال قبل استخدامه.', copied: 'تم النسخ', overview: 'نظرة عامة', security: 'الأمان', appearance: 'المظهر واللغة'
  },
  en: {
    login: 'Login', email: 'Email', password: 'Password', dashboard: 'Home', chat: 'Chats', providers: 'Providers', integrations: 'Integrations', terminal: 'Terminal', settings: 'Settings', send: 'Send', newChat: 'New chat', addProvider: 'Save provider', addIntegration: 'Save integration', model: 'Model', type: 'Type', apiKey: 'API key', baseUrl: 'API URL', name: 'Name', welcome: 'Welcome to Moataz AI', hero: 'A unified platform for chats, agents, model providers, GitHub and Telegram.', save: 'Save', tools: 'Tools', light: 'Light', dark: 'Dark', language: 'Language', message: 'Write a message or task…', theme: 'Appearance', logout: 'Logout', loading: 'Loading…', testConnection: 'Test connection', testing: 'Testing…', saving: 'Saving…', verified: 'Verified', failed: 'Failed', untested: 'Untested', edit: 'Edit', delete: 'Delete', cancel: 'Cancel', refresh: 'Refresh', status: 'Status', providerRequired: 'Add or select a provider for this conversation.', noProviders: 'No providers yet.', noIntegrations: 'No integrations yet.', noChats: 'Start a new conversation.', chatMode: 'Conversation mode', agentMode: 'Agent with tools', simpleChat: 'Simple chat', selectProvider: 'Select provider', selectModel: 'Model', connectionSuccessful: 'Connection successful', token: 'Token', allowedChatIds: 'Allowed Telegram chat IDs', allowedChatIdsHint: 'Separate IDs with commas. At least one ID is required for polling.', integrationIdentity: 'Integration identity', systemHealth: 'System health', database: 'Database', uptime: 'Uptime', configuredProviders: 'Configured providers', telegramBots: 'Telegram bots', available: 'Available', unavailable: 'Unavailable', terminalDisabled: 'The terminal is disabled in production without an external sandbox.', menu: 'Menu', close: 'Close', retry: 'Retry', clear: 'Clear', conversationSettings: 'Conversation settings', providerSaved: 'Provider saved. Test it before using it.', integrationSaved: 'Integration saved. Test it before using it.', copied: 'Copied', overview: 'Overview', security: 'Security', appearance: 'Appearance and language'
  }
} as const;

export type Language = keyof typeof dict;
export type TranslationKey = keyof typeof dict.en;

export function useT(lang: Language) {
  return (key: TranslationKey): string => dict[lang][key] ?? key;
}
